// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Simple.XChart.RoL.EFCore;

#nullable disable

namespace Simple.XChart.RoL.EFCore.Migrations
{
    [DbContext(typeof(RoLDBContext))]
    partial class RoLDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Simple.XChart.RoL.Common.Entities.AppInformation", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Code");

                    b.ToTable("AppInformations");

                    b.HasData(
                        new
                        {
                            Code = "PhotoTheme",
                            DateUpdated = new DateTime(2024, 3, 16, 8, 7, 29, 288, DateTimeKind.Local).AddTicks(3002),
                            Information = "natural landscape"
                        });
                });

            modelBuilder.Entity("Simple.XChart.RoL.Common.Entities.AttachVerse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BibleId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BookId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChapterId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MyActionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerseId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AttachVerses");
                });

            modelBuilder.Entity("Simple.XChart.RoL.Common.Entities.BannerImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AverageColor")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageAlt")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImageLandscapeUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Photographer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhotographerUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("BannerImages");
                });

            modelBuilder.Entity("Simple.XChart.RoL.Common.Entities.Chart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Charts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateEnd = new DateTime(2024, 7, 14, 8, 7, 29, 288, DateTimeKind.Local).AddTicks(2955),
                            DateStart = new DateTime(2024, 3, 16, 8, 7, 29, 288, DateTimeKind.Local).AddTicks(2930),
                            Description = "Guide thru Easter",
                            Title = "Lent"
                        });
                });

            modelBuilder.Entity("Simple.XChart.RoL.Common.Entities.ChartGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ChartId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChartId = 1,
                            Description = "Be With Jesus"
                        },
                        new
                        {
                            Id = 2,
                            ChartId = 1,
                            Description = "Become Like Jesus"
                        },
                        new
                        {
                            Id = 3,
                            ChartId = 1,
                            Description = "Do what Jesus did"
                        });
                });

            modelBuilder.Entity("Simple.XChart.RoL.Common.Entities.ChartOccurence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DaysCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Occurences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DaysCount = 1,
                            Description = "Daily"
                        },
                        new
                        {
                            Id = 2,
                            DaysCount = 7,
                            Description = "Weekly"
                        },
                        new
                        {
                            Id = 3,
                            DaysCount = 30,
                            Description = "Montly"
                        });
                });

            modelBuilder.Entity("Simple.XChart.RoL.Common.Entities.ChartPractice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("GoalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Practices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Silence & Solitude",
                            GoalId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Scripture",
                            GoalId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Prayer",
                            GoalId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Community",
                            GoalId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sabbath",
                            GoalId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Vocation",
                            GoalId = 3
                        },
                        new
                        {
                            Id = 7,
                            Description = "Hospitality",
                            GoalId = 3
                        },
                        new
                        {
                            Id = 8,
                            Description = "Simplicity",
                            GoalId = 3
                        });
                });

            modelBuilder.Entity("Simple.XChart.RoL.Common.Entities.MyAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OccurenceId")
                        .HasColumnType("int");

                    b.Property<int>("PracticeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("MyActions");
                });
#pragma warning restore 612, 618
        }
    }
}
